import requests
import json
import copy
import pprint
import torch
from PIL import Image

import sys
import warnings
import os

from utils import load_and_preprocess_dataset, setup_models, deduplicate_qars, setup_final_judge

def judge_qars(qars, image, judge_mllm):
    qars = judge_mllm.evaluate(qars, image)
    return qars

def verify_inference(qars, image, br_mllm):
    qars = br_mllm.verify_inference(qars, image)
    return qars

def generate_qars(dataset, generator_models, judge_model, br_model):
    # TODO: load aokvqa/scienceqa dataset
    # step 0: load and preprocess dataset
    #data = load_and_preprocess_dataset(dataset)
    url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/0052a70beed5bf71b92610a43a52df6d286cd5f3/diffusers/rabbit.jpg"
    image = Image.open(requests.get(url, stream=True).raw)

    # Step 1: Load models
    #generator_mllms, judge_mllm, br_mllm = setup_models(generator_models, judge_model, br_model)

    final_judge_mllm = setup_final_judge()

    '''
    # Step 2: Generate qars
    # query = "Can you describe the activity of the animal in context of the image?"
    #query = "Can you generate 3 non-trivial, diverse questions and corresponding answers based on the image without hallucinating? Keep the answers precise and short (no over explanation).Return the question-answer pairs in a list following this structure: [{'question': <question>, 'answer': <answer>}]. Return only the list of JSON objects, nothing else."
    query_1 = "Can you generate 3 non-trivial, diverse questions based on the image without hallucinating?  Each question can not have sub-questions. Return the questions in a list (comma separated) like this: [<question 1>, <question 2>, <question 3>]. Return only the list of questions, nothing else."
    query_2 = 'You will be given an image and 3 questions that are based on the image. For each question generate correct answer and corresponding brief rationale (rationale should justify briefly why the answer is correct) without hallucinating. Keep the answers precise and short (no over explanation). Return the question, answer, rationale triplets in a list following this structure: [{"question": <given question>, "answer": <corresponding correct answer>, "rationale": <corresponding rationale>}]. Return only the list of JSON objects, nothing else.'
    all_syn_qars = {}
    for i, mllm in enumerate(generator_mllms):
        questions = mllm.generate(image, query_1, questions=None)
        syn_qars = mllm.generate(image, query_2, questions)
        syn_qars = json.loads(syn_qars)
        all_syn_qars[f'mllm_{i+1}'] = {}
        for j, qar in enumerate(syn_qars):
            all_syn_qars[f'mllm_{i+1}'][f'qar_{j+1}'] = qar

    # Step 3: Judge (soft filter) qars generated by each generator mllm
    for mllm in all_syn_qars:
        judged_qars = []
        syn_qars = []
        for qar in all_syn_qars[mllm]:
            syn_qars.append(all_syn_qars[mllm][qar])

        judged_qars = judge_qars(syn_qars, image, judge_mllm)
        
        i = 0
        for qar in all_syn_qars[mllm]:
            all_syn_qars[mllm][qar] = judged_qars[i]
            i += 1

    # Step 4: Do inference verification using backward reasoner mllm
    for mllm in all_syn_qars:
        inference_verified_qars = []
        judged_syn_qars = []
        for qar in all_syn_qars[mllm]:
            judged_syn_qars.append(all_syn_qars[mllm][qar])
        inference_verified_qars = verify_inference(judged_syn_qars, image, br_mllm)
        
        i = 0
        for qar in all_syn_qars[mllm]:
            all_syn_qars[mllm][qar] = inference_verified_qars[i]
            i += 1

    # step 5: keep all filtered in quality qars
    syn_qar_bucket = []
    for mllm in all_syn_qars:
        for qar in all_syn_qars[mllm]:
            if (all_syn_qars[mllm][qar]['br_score'] > 0.7):
                syn_qar_bucket.append(all_syn_qars[mllm][qar])

    # step 6: de-duplicate initially filtered qars
    #unique_qars = deduplicate_qars(syn_qar_bucket)
    '''

    unique_qars = [
        {
            'question': 'What is the animal depicted in the image?', 
            'answer': 'A rabbit', 
            'rationale': 'The animal has long ears, large eyes, and a fluffy tail, which are characteristic features of a rabbit.', 
            'score': 90, 
            'feedback': "The image shows a rabbit standing on a dirt path with a house in the background. The rabbit is dressed in a blue coat and brown pants, which is not typical for a rabbit in the wild. The answer 'A rabbit' is correct because the animal's physical characteristics match those of a rabbit.", 
            'br_score': 65.5821
        }, 
        {
            'question': 'Where is the rabbit standing?', 
            'answer': 'On a dirt path', 
            'rationale': 'The rabbit is standing on a dirt path that runs through a grassy field, with flowers and trees on either side.', 
            'score': 90, 
            'feedback': 'The rabbit is standing on a dirt path that is surrounded by a lush green field with flowers and trees on either side. The path appears to be a rural road, leading towards a stone building in the distance. The rabbit is dressed in a blue coat and brown pants, which adds a touch of human-like formality to the scene. The overall setting suggests a peaceful countryside environment.', 
            'br_score': 78.8562
        }, 
        {
            'question': 'What is the rabbit wearing?', 
            'answer': 'A blue coat', 
            'rationale': 'The rabbit is wearing a blue coat with a brown vest and tan pants, which suggests a formal or semi-formal outfit.', 
            'score': 90, 
            'feedback': "The rabbit is dressed in a blue coat with a brown vest and tan pants, which is a formal or semi-formal outfit. The coat has buttons and a collar, and the rabbit is also wearing a bow tie, which adds to the formal appearance. The outfit is well-fitted and the rabbit is standing upright, which indicates that the clothing is designed to be worn by a human, not a rabbit. The colors are vibrant and the rabbit's attire is the focal point of the image, making it easy to identify.", 
            'br_score': 88.14959999999999
        }
    ]

    final_judge_mllm.evaluate(unique_qars, image)

     